application:
  swagger-open: true
  sign-open: true #签名机制是否开启(true或false)
  message:
    captch.template: SMS_150742325
  auth:
    enable: true #jwt鉴权机制是否开启(true或者false)
    header: Authorization #http请求头所需要的字段
    secret: kc-secret-!q2W        #jwt秘钥
    expiration: 604800      #7天 单位:秒
    path: auth         #认证请求的路径
    md5-key: randomKey      #md5加密混淆key
    exclude-pattern:
      - /webjars/**
      - /swagger*/**
      - /swagger*.*
      - /v2/**
      - /csrf/**
      - /member/regist

server:
  port: 8081 #项目端口
  servlet:
    context-path: /api
  tomcat:
    max-connections: 1024
    uri-encoding: UTF-8
    accept-count: 768
    max-threads: 1024

spring:
  profiles:
    active: local

mybatis-plus:
  typeAliasesPackage: com.stylefeng.guns.modular.system.model
  mapperLocations: classpath*:mapper/*.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

spring:
  messages:
    always-use-message-format: true
    basename: i18n/messages
    cache-seconds: 60
    encoding: UTF-8
    fallback-to-system-locale: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://39.108.237.254:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: db_user_devep
    password: rootQAZxsw
    db-name: guns #用来搜集数据库的所有表
    type: com.zaxxer.hikari.HikariDataSource
    hikari.minimum-idle: 5
    hikari.maximum-pool-size: 15
    hikari.auto-commit: true
    hikari.idle-timeout: 30000
    hikari.pool-name: EduCP
    hikari.max-lifetime: 1800000
    hikari.connection-timeout: 30000
    hikari.connection-test-query: SELECT 1
    filters: wall,mergeStat

logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: guns-rest.log
